# Generated by Django 4.0.2 on 2022-02-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hash', models.CharField(max_length=20, verbose_name='Hash')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('username', models.CharField(max_length=110, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone number')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('level', models.IntegerField(choices=[(1, 'MANAGER'), (2, 'ADMIN'), (3, 'WRITER'), (4, 'COMMON')], default=4, verbose_name='Level')),
                ('avatar', models.ImageField(upload_to='user/avatar', verbose_name='Avatar')),
                ('verify_phone_number', models.BooleanField(default=False, verbose_name='Verify phone number')),
                ('verify_email', models.BooleanField(default=False, verbose_name='Verify email')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
