# Generated by Django 4.0.2 on 2022-04-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.ImageField(null=True, upload_to='user/banner', verbose_name='Avatar'),
        ),
    ]
