# Generated by Django 4.0.2 on 2022-04-11 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hash', models.CharField(max_length=20, verbose_name='Hash')),
                ('accept', models.IntegerField(choices=[(1, 'TRUE'), (0, 'FLASE')], default=0, verbose_name='accept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writer_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
