# Generated by Django 4.0.2 on 2022-03-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hash', models.CharField(max_length=20, verbose_name='Hash')),
                ('receiver_email', models.EmailField(max_length=254)),
                ('email_type', models.IntegerField(choices=[(1, 'EMAIL VERIFY'), (2, 'FORGET PASSWORD')])),
                ('email_content', models.CharField(max_length=50000)),
                ('email_subject', models.CharField(max_length=200)),
                ('email_detail', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
