# Generated by Django 4.0.2 on 2022-03-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(1, 'EMAIL VERIFY'), (2, 'FORGET PASSWORD'), (3, 'NEW USER')]),
        ),
    ]
