# Generated by Django 4.0.2 on 2022-02-26 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hash', models.CharField(max_length=20, verbose_name='Hash')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hash', models.CharField(max_length=20, verbose_name='Hash')),
                ('report_object_type', models.IntegerField(choices=[(1, 'POST'), (2, 'COMMENT')], verbose_name='Object type')),
                ('report_type', models.IntegerField(choices=[(1, 'POST'), (2, 'COMMENT'), (3, 'INAPPROPRIATE'), (4, 'OTHER')], verbose_name='Report type')),
                ('body', models.CharField(max_length=1000, verbose_name='Body')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hash', models.CharField(max_length=20, verbose_name='Hash')),
                ('status', models.IntegerField(choices=[(1, 'PUBLISHED'), (2, 'AWAITING APPROVAL'), (3, 'DELETE BY AUTHOR'), (4, 'DISAPPROVAL'), (5, 'HIDDEN'), (6, 'REPORT'), (7, 'REVIEW')], verbose_name='Status')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('body', models.CharField(max_length=100000, verbose_name='Body')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='Like count')),
                ('bookmark_count', models.PositiveIntegerField(default=0, verbose_name='Bookmark count')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='Comment count')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='View count')),
                ('reading_time', models.PositiveIntegerField(verbose_name='Reading time')),
                ('published_at', models.DateTimeField(verbose_name='Published at')),
                ('cover', models.ImageField(upload_to='post/cover/%Y/%m', verbose_name='cover')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('main_tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_main_tag', to='blog.tag', verbose_name='Main tag')),
                ('tags', models.ManyToManyField(related_name='posts_tags', to='blog.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hash', models.CharField(max_length=20, verbose_name='Hash')),
                ('likeable_id', models.IntegerField(verbose_name='Likeable ID')),
                ('likeable_type', models.IntegerField(choices=[(1, 'POST'), (2, 'COMMENT')], verbose_name='Likeable type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hash', models.CharField(max_length=20, verbose_name='Hash')),
                ('body', models.CharField(max_length=2000, verbose_name='Body')),
                ('like_count', models.IntegerField(default=0, verbose_name='Like count')),
                ('comment_count', models.IntegerField(default=0, verbose_name='Comment count')),
                ('published_at', models.DateTimeField(verbose_name='Published at')),
                ('status', models.IntegerField(choices=[(1, 'PUBLISHED'), (2, 'AWAITING APPROVAL'), (3, 'DELETE BY AUTHOR'), (4, 'DISAPPROVAL'), (5, 'HIDDEN'), (6, 'REPORT'), (7, 'REVIEW')], verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.comment', verbose_name='childes')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='blog.post', verbose_name='Post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('hash', models.CharField(max_length=20, verbose_name='Hash')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookmarks', to='blog.post', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
