# Generated by Django 4.0.2 on 2022-02-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(1, 'PUBLISHED'), (2, 'AWAITING APPROVAL'), (3, 'DELETE BY AUTHOR'), (4, 'DISAPPROVAL'), (5, 'HIDDEN'), (6, 'REPORT'), (7, 'REVIEW')], default=1, verbose_name='Status'),
        ),
    ]
