# Generated by Django 4.0.2 on 2022-02-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_at',
            field=models.DateTimeField(verbose_name='Published at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(1, 'PUBLISHED'), (2, 'AWAITING APPROVAL'), (3, 'DELETE BY AUTHOR'), (4, 'DISAPPROVAL'), (5, 'HIDDEN'), (6, 'REPORT'), (7, 'REVIEW')], verbose_name='Status'),
        ),
    ]
