# Generated by Django 4.0.2 on 2022-03-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_published_at_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.JSONField(verbose_name='Body'),
        ),
    ]
