# Generated by Django 4.0.2 on 2022-04-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=None, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.JSONField(default=dict, verbose_name='Body'),
        ),
    ]
