# Generated by Django 4.0.2 on 2022-04-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_report_report_object_id_alter_comment_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=50000, verbose_name='Body'),
        ),
    ]
