# Generated by Django 4.0.2 on 2022-04-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(null=True, upload_to='tag/images', verbose_name='image'),
        ),
    ]
