# Generated by Django 4.0.2 on 2022-04-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_social_alter_setting_key_alter_team_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='key',
            field=models.CharField(default='social', max_length=100),
        ),
    ]
