# Generated by Django 4.0.2 on 2022-04-13 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_social_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='icon',
            field=models.CharField(default='lab la-instagram', max_length=50),
        ),
    ]
