# Generated by Django 4.0.2 on 2022-02-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='path',
            new_name='url',
        ),
    ]
